<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>False</BadObjectCC><Advice>Not available. More info may be in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>3b2bf86027a744643ebe32</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-04-18 20:23:05</createtime><buildsignature>Local.Unknown.Unknown.1.91.186.1030-1.200.000.572.Release</buildsignature><categoryid>posture.py:2375</categoryid><desyncid>3b2bf86027a744643ebe32</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: Posture Exit(posture_CarryNothing:1668) called multiple times without a paired entry or never called (PrimitiveCreated: True). Sim ID: 52654238772785227. Last affordance: &lt;class 'sims4.tuning.instances.idle_Hygiene'&gt;. Current lot description id: 122143.)&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 216, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2375, in _do_end&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2362, in get_endRuntimeError: Posture Exit(posture_CarryNothing:1668) called multiple times without a paired entry or never called (PrimitiveCreated: True). Sim ID: 52654238772785227. Last affordance: &lt;class 'sims4.tuning.instances.idle_Hygiene'&gt;. Current lot description id: 122143.rtim=0&#13;&#10;Client Session Time: 19.50&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 10,5,96,47512&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 11 10.0.22621 GPU: NVIDIA GeForce RTX 3060 Ti nvldumdx.dll 31.0.15.3141, GUID: D7B71E3E-6789-11CF-2B7F-F4360EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>3b2bf86027a744643ebe32</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-04-19 00:38:56</createtime><buildsignature>Local.Unknown.Unknown.1.91.186.1030-1.200.000.572.Release</buildsignature><categoryid>part.py:258</categoryid><desyncid>3b2bf86027a744643ebe32</desyncid><systemconfig/><screenshot/><desyncdata>Exception in &lt;function c_api_set_object_location_ex at 0x00007DF4BEA068C0&gt;, args: (13247741215592400, 662891993780121625, {2F10C01D3B4FD0,0,World}, Transform(Vector3(405.575104, 157.000793, 424.675140), Quaternion(0.000000, 0.707107, 0.000000, 0.707107)), 0, (0, 0), 0), kwargs: {}&#13;&#10;KeyError('Unable to find joint b__subroot__9 on object_bedDoubleCLLeather_01:0x093310c195b6f019[8]') (KeyError: 'Unable to find joint b__subroot__9 on object_bedDoubleCLLeather_01:0x093310c195b6f019[8]')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "obfuscated\src\sims4multiplayer\decorator\try_catch.py", line 8, in O0OOOOO0OOO00O0O0&#13;&#10;  File "obfuscated\src\sims4multiplayer\decorator\networked.py", line 31, in _O0O0000OOO00OO0OO&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 183, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\build_buy.py", line 1164, in c_api_set_object_location_ex&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 1560, in set_parent&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 355, in location&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 410, in set_location_without_distribution&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\part.py", line 798, in on_owner_location_changed&#13;&#10;  File "D:\Projects\Sims 4 Modding\Mods\TMex Mods 2022\Tmex-BetterExceptions\PublicUnlock.py", line 13, in _unlock&#13;&#10;  File "D:\Projects\Sims 4 Modding\Mods\TMex Mods 2022\Tmex-BetterExceptions\tmex_BetterExceptions_Hooks.py", line 88, in tm_be_object_joint_exceptions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\part.py", line 258, in get_joint_transform&#13;&#10;KeyError: 'Unable to find joint b__subroot__9 on object_bedDoubleCLLeather_01:0x093310c195b6f019[8]'rtim=0&#13;&#10;Client Session Time: 19.50&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 10,5,96,47512&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 11 10.0.22621 GPU: NVIDIA GeForce RTX 3060 Ti nvldumdx.dll 31.0.15.3141, GUID: D7B71E3E-6789-11CF-2B7F-F4360EC2D235&#13; &#10;</desyncdata></report>
</root>